name: Serve index.html
'on':
  - push
  - pull_request
jobs:
  test-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install HTTP server
        run: npm install -g http-server
      - name: Start HTTP server
        run: http-server -p 8080 &
      - name: Wait and test
        run: 'curl -I http://localhost:8080/index.html'
